### PR TITLE
Improvements to default behavior.

### PR DESCRIPTION
**Pull request by GarthDB**
Moving @misterbrownlee 's work to a new branch so we can collaborate better.

From https://github.com/topcoat/topdoc/pull/39

### CODE REVIEW

**Comment by GarthDB** [comment]
So I like the clobber flag, which ends up in the before function, but I'm thinking we take that out of the template index.js so it's just a standard behavior that can be used by topdoc regardless of the template.

**Comment by misterbrownlee** [comment]
Makes sense to me.  You have a much higher view of things than my recent deep dive.

**Comment by misterbrownlee** [comment]
Do you want me to fix the failing tests?  Or are you on that?

**Comment by GarthDB** [comment]
I'm on it. I fixed the broken ones and started adding more to get better
code coverage.

**Comment by misterbrownlee** [comment]
🎉

**Pull request merged**
